spring.application.name=SeXurityPOC


spring.datasource.url=jdbc:postgresql://ep-empty-poetry-a1azb2b0-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_P3jpIxC1mYuq&sslmode=require&channelBinding=require
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
logging.level.org.springframework.security=trace

jwt.rsa-private-key=classpath:certs/privateKey.pem
jwt.rsa-public-key=classpath:certs/publicKey.pem


